/*  
Autor: Daniel Felipe López Rendón 
Fecha de creación: 2025-02-04  
Descripción:  
En este archivo se encuentran los scripts correspondientes para la creación de un esquema para prueba técnica,dentro del 
cual se encuentran  las tablas que hacen alución a una entidad financiera basica. 
*/
CREATE TABLE CLIENT (
    ID_CLIENT NUMBER PRIMARY KEY AUTO_INCREMENT, 
    EMAIL VARCHAR(100) NOT NULL UNIQUE, 
    NAME VARCHAR(100) NOT NULL, 
    IDENTIFICATION_NUMBER NUMBER NOT NULL UNIQUE, 
    ADDRESS VARCHAR(255) NOT NULL, 
    PHONE VARCHAR(15), 
    STATUS CHAR(1) DEFAULT 'A' NOT NULL
);

-- Tabla ACCOUNT_TYPE
CREATE TABLE ACCOUNT_TYPE (
    ID_ACCOUNT_TYPE NUMBER PRIMARY KEY AUTO_INCREMENT, 
    DESCRIPTION VARCHAR(255) NOT NULL, 
    NAME VARCHAR(100) NOT NULL UNIQUE, 
    STATUS CHAR(1) DEFAULT 'A' NOT NULL
);

-- Tabla ACCOUNT
CREATE TABLE ACCOUNT (
    ID_ACCOUNT NUMBER PRIMARY KEY AUTO_INCREMENT, 
    ID_CLIENT NUMBER NOT NULL, 
    ACCOUNT_NUMBER NUMBER NOT NULL, 
    ID_ACCOUNT_TYPE NUMBER NOT NULL, 
    STATUS CHAR(1) DEFAULT 'A' NOT NULL, 
    BALANCE DECIMAL(15,2) NOT NULL, 
    CONSTRAINT FK_ACCOUNT_CLIENT FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
    CONSTRAINT FK_ACCOUNT_TYPE FOREIGN KEY (ID_ACCOUNT_TYPE) REFERENCES ACCOUNT_TYPE(ID_ACCOUNT_TYPE),
    CONSTRAINT UK_ACCOUNT_NUMBER UNIQUE (ACCOUNT_NUMBER, ID_ACCOUNT_TYPE)
);

-- Tabla TRANSACTION_TYPE
CREATE TABLE TRANSACTION_TYPE (
    ID_TRANSACTION_TYPE NUMBER PRIMARY KEY AUTO_INCREMENT, 
    DESCRIPTION VARCHAR(255) NOT NULL, 
    NAME VARCHAR(100) NOT NULL UNIQUE, 
    STATUS CHAR(1) DEFAULT 'A' NOT NULL
);

-- Tabla ACCOUNT_MOVEMENT
CREATE TABLE ACCOUNT_MOVEMENT (
    ID_ACCOUNT_MOVEMENT NUMBER PRIMARY KEY AUTO_INCREMENT, 
    ID_ACCOUNT NUMBER NOT NULL, 
    ID_TRANSACTION_TYPE NUMBER NOT NULL, 
    AMOUNT DECIMAL(15,2) NOT NULL, 
    TRANSACTION_DATE TIMESTAMP NOT NULL, 
    CONSTRAINT FK_MOVEMENT_ACCOUNT FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNT(ID_ACCOUNT),
    CONSTRAINT FK_MOVEMENT_TRANSACTION FOREIGN KEY (ID_TRANSACTION_TYPE) REFERENCES TRANSACTION_TYPE(ID_TRANSACTION_TYPE)
);


CREATE SEQUENCE SEQ_CLIENT
START WITH 1
INCREMENT BY 1;